src/dotnet/ClientUI/Models/ErrorViewModel.cs
namespace ClientUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/dotnet/ClientUI/ViewModels/ConfigViewModel.cs
namespace ClientUI.Controllers
{
    public class ConfigViewModel
    {
        public string Value { get; set; }
    }
}

src/dotnet/ClientUI/Controllers/ConfigController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;

namespace ClientUI.Controllers
{
    public class ConfigController : Controller
    {
        private readonly IConfiguration _configuration;

        public ConfigController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public ViewResult Index()
        {
            return View();
        }

        public ViewResult FromAppSettings()
        {
            var model = new ConfigViewModel
            {
                Value = _configuration["ClientUI:FromAppSettingsValue"]
            };

            return View(model);
        }

        public ViewResult FromAppSettingsEnvironment()
        {
            var model = new ConfigViewModel
            {
                Value = _configuration["ClientUI:FromAppSettingsEnvironmentValue"]
            };

            return View(model);
        }

        public ViewResult FromUserSecrets()
        {
            var model = new ConfigViewModel
            {
                Value = _configuration["ClientUI:FromUserSecrets"]
            };

            return View(model);
        }

        public ViewResult FromEnvironmentVariables()
        {
            var model = new ConfigViewModel
            {
                Value = _configuration["ClientUI:FromEnvironmentVariables"]
            };

            return View(model);
        }
    }
}

src/dotnet/ClientUI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ClientUI.Models;

namespace ClientUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/dotnet/ClientUI/Views/Config/FromAppSettings.cshtml
@model ClientUI.Controllers.ConfigViewModel

@{
    ViewData["Title"] = "Config value from appsettings.json";
}

<h1>Config value from appsettings.json</h1>

<p>For this example to work properly, you must have:</p>
<ul>
    <li>A configuration value named ClientUI:FromAppSettings in appsettings.json.</li>
</ul>

<div class="card">
    <div class="card-header">
        <strong>Configuration Value</strong>:  @Model.Value
    </div>
</div>

src/dotnet/ClientUI/Views/Config/FromAppSettingsEnvironment.cshtml
@model ClientUI.Controllers.ConfigViewModel

@{
    ViewData["Title"] = "Config value from appsettings.[Environment].json";
}

<h1>Config value from appsettings.[Environment].json</h1>

<p>For this example to work properly, you must have:</p>
<ul>
    <li>A configuration value named ClientUI:FromAppSettingsEnvironment in appsettings.json.  This value will be overriden by another value in appsettings.Development.json.</li>
    <li>A different configuration value named ClientUI:FromAppSettingsEnvironment in appsettings.Development.json.  This will be the final configuration value.</li>
</ul>

<div class="card">
    <div class="card-header">
        <strong>Configuration Value</strong>:  @Model.Value
    </div>
</div>

src/dotnet/ClientUI/Views/Config/FromEnvironmentVariables.cshtml
@model ClientUI.Controllers.ConfigViewModel

@{
    ViewData["Title"] = "Config value from environment variables";
}

<h1>Config value from environment variables</h1>

<p>For this example to work properly, you must have:</p>
<ul>
    <li>A configuration value named ClientUI:FromEnvironmentVariables in appsettings.json.  This value will be overriden by another value in appsettings.Development.json.</li>
    <li>A different configuration value named ClientUI:FromEnvironmentVariables in appsettings.Development.json.  This value will be overriden by another value in a user secret during development only.</li>
    <li>A different configuration value in a user secret named ClientUI:FromEnvironmentVariables.  Create this by running 'dotnet user-secrets set ClientUI:FromEnvironmentVariables "This value is from user secrets."'  This value will be overriden by another value in an environment variable.</li>
    <li>A different configuration value in an environment variable named ClientUI:FromEnvironmentVariables.  This will be the final configuration value.
        <ul>
            <li>On Windows, you can create this by running 'setx ClientUI:FromEnvironmentVariables "This value is from environment variables"' and restarting your IDE.</li>
            <li>On most flavors of Linux, you can create this by putting the following in your ~/.profile and rebooting:  export ClientUI__FromEnvironmentVariables="This value is from environment variables"</li>
        </ul>
    </li>
</ul>

<div class="card">
    <div class="card-header">
        <strong>Configuration Value</strong>:  @Model.Value
    </div>
</div>

src/dotnet/ClientUI/Views/Config/FromUserSecrets.cshtml
@model ClientUI.Controllers.ConfigViewModel

@{
    ViewData["Title"] = "Config value from user secrets";
}

<h1>Config value from user secrets</h1>

<p>For this example to work properly, you must have:</p>
<ul>
    <li>A configuration value named ClientUI:FromUserSecrets in appsettings.json.  This value will be overriden by another value in appsettings.Development.json.</li>
    <li>A different configuration value named ClientUI:FromUserSecrets in appsettings.Development.json.  This value will be overriden by another value in a user secret during development only.</li>
    <li>A different configuration value in a user secret named ClientUI:FromUserSecrets.  Create this by running 'dotnet user-secrets set ClientUI:FromUserSecrets "This value is from user secrets"'.  This will be the final configuration value.</li>
</ul>

<div class="card">
    <div class="card-header">
        <strong>Configuration Value</strong>:  @Model.Value
    </div>
</div>

src/dotnet/ClientUI/Views/Config/Index.cshtml
@{
    ViewData["Title"] = "Configuration Examples";
}

<div class="text-center">
    <h1 class="display-4">Configuration Examples:</h1>
    <p><a class="nav-link" asp-area="" asp-controller="Config" asp-action="FromAppSettings">From appsettings.json</a></p>

    <p><a class="nav-link" asp-area="" asp-controller="Config" asp-action="FromAppSettingsEnvironment">From appsettings.[Environment].json</a></p>
    
    <p><a class="nav-link" asp-area="" asp-controller="Config" asp-action="FromUserSecrets">From user secrets</a></p>
    
    <p><a class="nav-link" asp-area="" asp-controller="Config" asp-action="FromEnvironmentVariables">From environment variables</a></p>
</div>

src/dotnet/ClientUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">12-Factor Application Examples</h1>
    <p>@Html.ActionLink("Configuration Examples", "Index", "Config")</p>
</div>

src/dotnet/ClientUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 12-Factor Application Examples</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Enterprise Products
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>